apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- releaseName: localrococo-bootnode-alice
  repo: "https://paritytech.github.io/helm-charts/"
  name: node
  version: 5.4.0
  additionalValuesFiles:
  - ../relaychain-common.yaml
  - localrococo-bootnode-alice.yaml
#- releaseName: localrococo-bootnode-bob
#  repo: "https://paritytech.github.io/helm-charts/"
#  name: node
#  version: 5.4.0
#  additionalValuesFiles:
#  - ../relaychain-common.yaml
#  - localrococo-bootnode-bob.yaml