apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- releaseName: localrococo-asset-hub-collator
  repo: "https://paritytech.github.io/helm-charts/"
  name: node
  version: 5.4.0
  additionalValuesFiles:
  - ../parachain-common.yaml
  - localrococo-asset-hub-collator.yaml
- releaseName: localrococo-tick-collator
  repo: "https://paritytech.github.io/helm-charts/"
  name: node
  version: 5.4.0
  additionalValuesFiles:
  - ../parachain-common.yaml
  - localrococo-tick-collator.yaml