apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
 chartHome: ../../charts

helmCharts:
- releaseName: testnet-manager
  repo: "https://paritytech.github.io/helm-charts/"
  name: testnet-manager
  version: 1.3.1
  #valuesInline: {}
  # old kustomize single value supported
  valuesFile: testnet-manager.yaml
  # kustomize v5+ required
#  additionalValuesFiles:
#  - manager/1.yaml
#  - manager/testnet-manager.yaml
- releaseName: chainspec
  name: chainspecs
  valuesFile: chainspecs.yaml