## nginx which hosts `polkadot build-spec` command output
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: {{ .Release.Name | trunc 63 | trimSuffix "-" }}
